### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by hrwakeford** [hrwakeford/ExoTiC-ISM#125]
Rename the master branch to main to follow the new guidelines for GitHub

**Comment by ivalaginja** [comment]
@hrwakeford this seems very easy to do, I have found example instructions here:
https://www.r-bloggers.com/2020/07/5-steps-to-change-github-default-branch-from-master-to-main/

Step 4 requires admin permissions though, as the new `main` branch will need to be assigned to be the default branch. Would you like me to do the first three steps, and then to reach out to you to finalize this?

**Comment by hrwakeford** [comment]
Yeah that sounds good to me if you have time to do the first steps I will get it all finished off.

**Comment by ivalaginja** [comment]
All right I'll get to it asap then, it doesn't seem to take much time. Will ping you when done.

**Comment by ivalaginja** [comment]
@hrwakeford I am done with the first three steps from the above link. I also remembered that we will have to reset the branch protection rule from master to main, could I ask you do to the following?

- On the repo, go to "Settings", and on the left to the menu button "Branches"
- on the right you will find the part "Branch protection rules: find the entry for master and click edit
- make a screenshot of those settings so that we can make sure we set up the same thing for main
- close without changing anything

Then, as it turns out, we do **not** have to do Step number 4 in the above link, since the default branch on this repository is develop anyway.
So please just take a note of the current branch protection rules for master, let me know when you're done and I will proceed by deleting the master branch from the remote.

Let me know if I can be of any assistance.

**Comment by hrwakeford** [comment]
I have screen shotted the settings we currently have. I assume you need to push the main branch and then remove the master branch. And then I go in and make sure the main branch has the same permissions and settings as before. 

Correct?

**Comment by ivalaginja** [comment]
That's exactly it. main is already pushed, I just need to delete master now. Do I have green lights from you to do that?
I have a full backup of the repo locally in case something goes wrong.

**Comment by hrwakeford** [comment]
yes please do that now :)

**Comment by ivalaginja** [comment]
Woops, we also need to un-protect the master branch first. Could you delete the branch protection rule for master?

**Comment by hrwakeford** [comment]
did that work?

**Comment by hrwakeford** [comment]
or if it is easier I can just press delete then you can push the main branch

**Comment by ivalaginja** [comment]
The main is already pushed, but I still can't delete the master branch for some reason.

**Comment by hrwakeford** [comment]
I believe I have now deleted master, left main, and updated the branch settings for main to mimic what we had for master.

This issue is now closed
